### ISSUE TITLE
界面数据显示bug

### ISSUE THREAD

**Issue by cfy3133** [yunfei07/lemon#10]
有大bug，界面需要强制刷新才会出数据

**Comment by yunfei07** [comment]
可否详细描述一下，哪个页面？最好能来个截图

**Comment by cfy3133** [comment]
![image](https://user-images.githubusercontent.com/43978367/173208404-6b53a32c-3cfa-4dfc-ab87-15d79769554d.png)

**Comment by yunfei07** [comment]
已修复
